version: '3.7'

services:
  db:
    container_name: db
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    container_name: app
    depends_on: [db]
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.dev
    image: tailwind-blog:latest
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
