version: '3.7'

services:
  db:
    container_name: db
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  app:
    links:
      - 'db:database'
    container_name: app
    depends_on: [db]
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.dev
    image: tailwind-blog:latest
    ports:
      - 3000:3000
      - 5555:5555 # Prisma Studio
    volumes:
      - .:/app
      - /app/node_modules
      - ./node_modules/@prisma/client:/app/node_modules/@prisma/client
      - /app/.next
